spring:
# 配置存储数据的mongoDB数据库连接
  data:
    mongodb:
      username: admin
      host: 39.99.206.180
      port: 27017
      password: admin
      database: glmall
  datasource:
      url: jdbc:mysql://10.90.1.211:3306/gl_third_party?characterEncoding=UTF-8&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: xiot
      password: Xiot@mariadb_2018