spring:
# 配置存储数据的mongoDB数据库连接
  data:
    mongodb:
      username: admin
      host: 39.99.206.180
      port: 27017
      password: admin
      database: glmall
  datasource:
      url: jdbc:mysql://10.90.1.211:3306/stock
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: xiot
      username: Xiot@mariadb_2018